### ISSUE TITLE
increasing the font size

### ISSUE THREAD

**Issue by tasdikrahman** [ashish1294/resume#1]
Hey @ashish1294 . Thanks for open sourcing your`tex` source files.

The issue I am facing is that when I take a print of this(after adding my mods). The font size turns out to be quite small. A possible solution would be to do a 

`\documentclass[12pt]{report}`

But in our source, we have it something like this

`\documentclass[margin, centered]{res}`

How should I do it in our case?

**Comment by ashish1294** [comment]
The default it 10pt. Currently, 2 other sizes are supported - 11pt and 12pt. To use them, change it to

\documentclass[margin, centered, 11pt]{res}
\documentclass[margin, centered, 12pt]{res}

No other sizes are supported. It is not worth implementing other sizes as resumes don't typically use larger fonts.

**Comment by tasdikrahman** [comment]
@ashish1294 Thanks :smile: 

Just one more. How can we change the line spacings between two lines? I mean when you are writing a para and you want to change the spacings between two lines ( If line width is the correct term for that. I tried out with `textwidth` inside the document. But that didn't work )

Just curious here. But didn't you find 10pt to be quite small when being printed?

**Comment by ashish1294** [comment]
Try \renewcommand{\baselinestretch}{1.5}
